# Generated by Django 4.0.5 on 2022-07-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegister',
            fields=[
                ('customer_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=40)),
                ('billing_address', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=50)),
                ('customer_status', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdminData',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user_password', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.DecimalField(decimal_places=0, max_digits=6)),
                ('roles', models.DecimalField(decimal_places=0, max_digits=1)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('user_IP', models.CharField(max_length=15)),
            ],
        ),
    ]
