# Generated by Django 4.0.6 on 2022-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidalendpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceManufacturingInfo',
            fields=[
                ('device_manufacture_date', models.DateTimeField(auto_created=True)),
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_status', models.IntegerField()),
                ('device_version', models.IntegerField()),
            ],
        ),
    ]
