# Generated by Django 4.1.1 on 2022-09-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tidalendpoints", "0003_alter_devicemanufacturinginfo_device_version"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomerRegister",),
        migrations.DeleteModel(name="DeviceManufacturingInfo",),
        migrations.DeleteModel(name="UserAdminData",),
    ]
